#!/bin/bash
# Quick Reference for Bitcorp ERP Development

echo "🚀 Bitcorp ERP - Quick Reference"
echo "================================="
echo ""
echo "📁 Just navigate to project directory:"
echo "   cd /Users/klm95441/Documents/asjad/BitCorp/bitcorp"
echo "   (Environment auto-activates with direnv!)"
echo ""
echo "🔧 Development Commands:"
echo "   ./scripts/dev.sh start     # Start all services"
echo "   ./scripts/dev.sh status    # Check status"
echo "   ./scripts/dev.sh backend   # Start backend only"
echo "   ./scripts/dev.sh clean     # Clean & stop all"
echo ""
echo "🌐 URLs:"
echo "   Backend:  http://localhost:8000"
echo "   Health:   http://localhost:8000/health"
echo "   API Docs: http://localhost:8000/docs"
echo "   pgAdmin:  http://localhost:5050"
echo ""
echo "🔐 Credentials:"
echo "   Developer: developer@bitcorp.com / developer123!"
echo "   Admin:     admin@bitcorp.com / admin123!"
echo ""
echo "🧪 Test Login:"
echo '   curl -X POST http://localhost:8000/api/v1/auth/login \'
echo '     -H "Content-Type: application/json" \'
echo '     -d '"'"'{"username": "developer@bitcorp.com", "password": "developer123!"}'"'"
echo ""
echo "✨ No more manual venv activation needed!"
